[package]
name = "backend"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.97"
jiff = { version = "0.2", features = ["serde"] }
jiff-sqlx = { version = "0.1.1", features = ["postgres"] }
rust_decimal = { version = "1.37.1", features = ["serde", "macros"] }
secrecy = { version = "0.10.3", features = ["serde"] }
serde_json = "1.0.140"
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-native-tls", "postgres", "uuid", "rust_decimal" ] }
sqlx-postgres = "0.8.3"
tokio = { version = "1.44.1", features = ["full"] }
uuid = { version = "1.16.0", features = ["v4"] }
