ALTER TABLE communities DROP COLUMN IF EXISTS stripe_customer_id;
DROP TABLE IF EXISTS community_storage_usage;
DROP TABLE IF EXISTS community_subscriptions;
DROP TYPE IF EXISTS BILLING_INTERVAL;
DROP TYPE IF EXISTS SUBSCRIPTION_STATUS;
DROP TYPE IF EXISTS SUBSCRIPTION_TIER;
ALTER TABLE site_images DROP COLUMN file_size;
